 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/jadwal_mata_kuliahs", type: :request do
  # JadwalMataKuliah. As you add validations to JadwalMataKuliah, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JadwalMataKuliah.create! valid_attributes
      get jadwal_mata_kuliahs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      jadwal_mata_kuliah = JadwalMataKuliah.create! valid_attributes
      get jadwal_mata_kuliah_url(jadwal_mata_kuliah)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_jadwal_mata_kuliah_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      jadwal_mata_kuliah = JadwalMataKuliah.create! valid_attributes
      get edit_jadwal_mata_kuliah_url(jadwal_mata_kuliah)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JadwalMataKuliah" do
        expect {
          post jadwal_mata_kuliahs_url, params: { jadwal_mata_kuliah: valid_attributes }
        }.to change(JadwalMataKuliah, :count).by(1)
      end

      it "redirects to the created jadwal_mata_kuliah" do
        post jadwal_mata_kuliahs_url, params: { jadwal_mata_kuliah: valid_attributes }
        expect(response).to redirect_to(jadwal_mata_kuliah_url(JadwalMataKuliah.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JadwalMataKuliah" do
        expect {
          post jadwal_mata_kuliahs_url, params: { jadwal_mata_kuliah: invalid_attributes }
        }.to change(JadwalMataKuliah, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post jadwal_mata_kuliahs_url, params: { jadwal_mata_kuliah: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jadwal_mata_kuliah" do
        jadwal_mata_kuliah = JadwalMataKuliah.create! valid_attributes
        patch jadwal_mata_kuliah_url(jadwal_mata_kuliah), params: { jadwal_mata_kuliah: new_attributes }
        jadwal_mata_kuliah.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the jadwal_mata_kuliah" do
        jadwal_mata_kuliah = JadwalMataKuliah.create! valid_attributes
        patch jadwal_mata_kuliah_url(jadwal_mata_kuliah), params: { jadwal_mata_kuliah: new_attributes }
        jadwal_mata_kuliah.reload
        expect(response).to redirect_to(jadwal_mata_kuliah_url(jadwal_mata_kuliah))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        jadwal_mata_kuliah = JadwalMataKuliah.create! valid_attributes
        patch jadwal_mata_kuliah_url(jadwal_mata_kuliah), params: { jadwal_mata_kuliah: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested jadwal_mata_kuliah" do
      jadwal_mata_kuliah = JadwalMataKuliah.create! valid_attributes
      expect {
        delete jadwal_mata_kuliah_url(jadwal_mata_kuliah)
      }.to change(JadwalMataKuliah, :count).by(-1)
    end

    it "redirects to the jadwal_mata_kuliahs list" do
      jadwal_mata_kuliah = JadwalMataKuliah.create! valid_attributes
      delete jadwal_mata_kuliah_url(jadwal_mata_kuliah)
      expect(response).to redirect_to(jadwal_mata_kuliahs_url)
    end
  end
end
