 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kategori_kuesioners", type: :request do
  # KategoriKuesioner. As you add validations to KategoriKuesioner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  before { sign_in FactoryBot.build_stubbed(:user, :admin) }

  describe "GET /index" do
    it "renders a successful response" do
      KategoriKuesioner.create! valid_attributes
      get kategori_kuesioners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kategori_kuesioner = KategoriKuesioner.create! valid_attributes
      get kategori_kuesioner_url(kategori_kuesioner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kategori_kuesioner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      kategori_kuesioner = KategoriKuesioner.create! valid_attributes
      get edit_kategori_kuesioner_url(kategori_kuesioner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new KategoriKuesioner" do
        expect {
          post kategori_kuesioners_url, params: { kategori_kuesioner: valid_attributes }
        }.to change(KategoriKuesioner, :count).by(1)
      end

      it "redirects to the created kategori_kuesioner" do
        post kategori_kuesioners_url, params: { kategori_kuesioner: valid_attributes }
        expect(response).to redirect_to(kategori_kuesioner_url(KategoriKuesioner.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new KategoriKuesioner" do
        expect {
          post kategori_kuesioners_url, params: { kategori_kuesioner: invalid_attributes }
        }.to change(KategoriKuesioner, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post kategori_kuesioners_url, params: { kategori_kuesioner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kategori_kuesioner" do
        kategori_kuesioner = KategoriKuesioner.create! valid_attributes
        patch kategori_kuesioner_url(kategori_kuesioner), params: { kategori_kuesioner: new_attributes }
        kategori_kuesioner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kategori_kuesioner" do
        kategori_kuesioner = KategoriKuesioner.create! valid_attributes
        patch kategori_kuesioner_url(kategori_kuesioner), params: { kategori_kuesioner: new_attributes }
        kategori_kuesioner.reload
        expect(response).to redirect_to(kategori_kuesioner_url(kategori_kuesioner))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        kategori_kuesioner = KategoriKuesioner.create! valid_attributes
        patch kategori_kuesioner_url(kategori_kuesioner), params: { kategori_kuesioner: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kategori_kuesioner" do
      kategori_kuesioner = KategoriKuesioner.create! valid_attributes
      expect {
        delete kategori_kuesioner_url(kategori_kuesioner)
      }.to change(KategoriKuesioner, :count).by(-1)
    end

    it "redirects to the kategori_kuesioners list" do
      kategori_kuesioner = KategoriKuesioner.create! valid_attributes
      delete kategori_kuesioner_url(kategori_kuesioner)
      expect(response).to redirect_to(kategori_kuesioners_url)
    end
  end
end
