 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kelas", type: :request do
  # Kelas. As you add validations to Kelas, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Kelas.create! valid_attributes
      get kelas_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kelas = Kelas.create! valid_attributes
      get kelas_url(kelas)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kelas_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      kelas = Kelas.create! valid_attributes
      get edit_kelas_url(kelas)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Kelas" do
        expect {
          post kelas_index_url, params: { kelas: valid_attributes }
        }.to change(Kelas, :count).by(1)
      end

      it "redirects to the created kelas" do
        post kelas_index_url, params: { kelas: valid_attributes }
        expect(response).to redirect_to(kelas_url(Kelas.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Kelas" do
        expect {
          post kelas_index_url, params: { kelas: invalid_attributes }
        }.to change(Kelas, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post kelas_index_url, params: { kelas: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kelas" do
        kelas = Kelas.create! valid_attributes
        patch kelas_url(kelas), params: { kelas: new_attributes }
        kelas.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kelas" do
        kelas = Kelas.create! valid_attributes
        patch kelas_url(kelas), params: { kelas: new_attributes }
        kelas.reload
        expect(response).to redirect_to(kelas_url(kelas))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        kelas = Kelas.create! valid_attributes
        patch kelas_url(kelas), params: { kelas: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kelas" do
      kelas = Kelas.create! valid_attributes
      expect {
        delete kelas_url(kelas)
      }.to change(Kelas, :count).by(-1)
    end

    it "redirects to the kelas list" do
      kelas = Kelas.create! valid_attributes
      delete kelas_url(kelas)
      expect(response).to redirect_to(kelas_index_url)
    end
  end
end
