 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tahun_akademiks", type: :request do
  # TahunAkademik. As you add validations to TahunAkademik, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TahunAkademik.create! valid_attributes
      get tahun_akademiks_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tahun_akademik = TahunAkademik.create! valid_attributes
      get tahun_akademik_url(tahun_akademik)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tahun_akademik_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tahun_akademik = TahunAkademik.create! valid_attributes
      get edit_tahun_akademik_url(tahun_akademik)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TahunAkademik" do
        expect {
          post tahun_akademiks_url, params: { tahun_akademik: valid_attributes }
        }.to change(TahunAkademik, :count).by(1)
      end

      it "redirects to the created tahun_akademik" do
        post tahun_akademiks_url, params: { tahun_akademik: valid_attributes }
        expect(response).to redirect_to(tahun_akademik_url(TahunAkademik.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TahunAkademik" do
        expect {
          post tahun_akademiks_url, params: { tahun_akademik: invalid_attributes }
        }.to change(TahunAkademik, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tahun_akademiks_url, params: { tahun_akademik: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tahun_akademik" do
        tahun_akademik = TahunAkademik.create! valid_attributes
        patch tahun_akademik_url(tahun_akademik), params: { tahun_akademik: new_attributes }
        tahun_akademik.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tahun_akademik" do
        tahun_akademik = TahunAkademik.create! valid_attributes
        patch tahun_akademik_url(tahun_akademik), params: { tahun_akademik: new_attributes }
        tahun_akademik.reload
        expect(response).to redirect_to(tahun_akademik_url(tahun_akademik))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tahun_akademik = TahunAkademik.create! valid_attributes
        patch tahun_akademik_url(tahun_akademik), params: { tahun_akademik: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tahun_akademik" do
      tahun_akademik = TahunAkademik.create! valid_attributes
      expect {
        delete tahun_akademik_url(tahun_akademik)
      }.to change(TahunAkademik, :count).by(-1)
    end

    it "redirects to the tahun_akademiks list" do
      tahun_akademik = TahunAkademik.create! valid_attributes
      delete tahun_akademik_url(tahun_akademik)
      expect(response).to redirect_to(tahun_akademiks_url)
    end
  end
end
