# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ dev, main ]
    paths-ignore: 
      - "**/README.md"
  pull_request:
    branches: [ dev, main ]
    paths-ignore: 
      - "**/README.md"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.15
    - name: Cache gem
      uses: pat-s/always-upload-cache@v2.1.3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.6.0
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails db:migrate
        bundle exec rspec
